from __future__ import annotations


DEFAULT_CONFIG: dict = {
    "display_language": "zh-CN",
    "api": {
        "key": "",
        "base_url": "https://sub.100xlabs.space/v1",
        "model": "claude-opus-4-8",
        "llm_support_json": True,
        "proxy_url": "",
    },
    "max_workers": 4,
    "llm_max_workers": 4,
    "tts_max_workers": 1,
    "target_language": "Simplified Chinese",
    "translation": {
        "publish_fast_chunk_lines": 30,
        "publish_fast_chunk_chars": 3000,
        "publish_fast_use_summary": True,
        "pacing_budget_enabled": False,
        "estimated_tts_chars_per_sec": 4.4,
        "estimated_zh_chars_per_en_word": 1.72,
        "min_zh_chars_per_en_word": 1.67,
        "natural_min_zh_chars_per_en_word": 1.70,
        "natural_max_zh_chars_per_en_word": 1.72,
        "soft_pressure_max_zh_chars_per_en_word": 1.75,
        "hard_pressure_max_zh_chars_per_en_word": 1.73,
        "critical_pressure_max_zh_chars_per_en_word": 1.70,
        "target_pacing_pressure": 1.05,
        "soft_pacing_pressure": 1.10,
        "hard_pacing_pressure": 1.18,
        "critical_pacing_pressure": 1.25,
        "min_pacing_source_sec": 20.0,
    },
    "demucs": True,
    "demucs_segment_minutes": 30,
    "whisper": {
        "model": "large-v3",
        "language": "en",
        "detected_language": "en",
        "runtime": "local",
        "print_progress": False,
        "whisperX_302_api_key": "",
        "elevenlabs_api_key": "",
    },
    "source": {
        "url_provider": "yt-dlp",
        "output_filename": "source_video.mp4",
        "yt_dlp_path": "yt-dlp",
        "resolution": "1080",
        "yt_dlp_extra_args": [],
        "auto_update_ytdlp": False,
        "write_thumbnail": False,
        "cookies_path": "",
        "cookies_from_browser": "firefox",
        "cookies_browser_profile": "",
        "socket_timeout": 20,
        "retries": 3,
        "use_python_api": True,
    },
    "youtube": {
        "cookies_path": "",
        "cookies_from_browser": "firefox",
        "cookies_browser_profile": "",
        "auto_update_ytdlp": False,
        "write_thumbnail": False,
        "socket_timeout": 20,
        "retries": 3,
    },
    "ytb_resolution": "1080",
    "subtitle": {
        "display_max_chars_per_line": 20,
        "display_source_max_chars_per_line": 42,
        "display_max_lines": 1,
    },
    "summary_length": 8000,
    "burn_subtitles": False,
    "ffmpeg_gpu": False,
    "batch": {
        "jobs_dir": "jobs",
        "max_active_jobs": 10,
        "download_workers": 3,
        "transcribe_workers": 1,
        "translate_workers": 1,
        "tts_prepare_workers": 1,
        "tts_workers": 1,
        "audio_mix_workers": 1,
        "compose_workers": 1,
        "poll_interval_sec": 3,
        "max_stage_retries": 1,
        "stage_idle_timeout_sec": 0,
        "download_idle_timeout_sec": 1800,
        "transcribe_idle_timeout_sec": 7200,
        "translate_idle_timeout_sec": 1800,
        "tts_prepare_idle_timeout_sec": 900,
        "tts_idle_timeout_sec": 1800,
        "audio_mix_idle_timeout_sec": 1800,
        "compose_idle_timeout_sec": 7200,
        "dependency_probe": True,
        "dependency_probe_ttl_sec": 30,
        "auto_requeue_failed": True,
        "failed_cooldown_sec": 300,
        "max_auto_requeues": 2,
    },
    "tts_method": "indextts",
    "tts_audio": {
        "merge_micro_lines": True,
        "merge_micro_line_chars": 6,
        "slow_fast_segments": False,
        "slow_fast_trigger_units_per_sec": 5.75,
        "slow_fast_target_units_per_sec": 5.4,
        "slow_fast_max_duration_factor": 1.1,
        "slow_fast_min_duration_sec": 1.2,
        "postprocess_audio": True,
        "trim_silence": True,
        "trim_silence_padding_ms": 260,
        "trim_min_silence_len_ms": 180,
        "trim_silence_threshold_offset_db": 22,
        "trim_silence_threshold_min_dbfs": -45,
        "peak_normalize_dbfs": -3.0,
        "lowpass_hz": 6800,
        "audio_quality_check": True,
        "generated_internal_silence_min_ms": 500,
        "generated_max_internal_silence_ms": 1200,
        "generated_max_internal_silence_ratio": 0.45,
    },
    "indextts": {
        "api_url": "http://127.0.0.1:8010/tts",
        "prompt_audio_mode": "auto_ref",
        "prompt_audio": "",
        "auto_prompt_strategy": "global_best",
        "auto_prompt_target_sec": 12,
        "auto_prompt_min_prompt_sec": 6,
        "auto_prompt_soft_min_single_sec": 5,
        "auto_prompt_min_segment_sec": 3,
        "auto_prompt_max_segment_sec": 16,
        "auto_prompt_edge_trim_ms": 700,
        "auto_prompt_min_active_ratio": 0.58,
        "auto_prompt_max_internal_silence_ms": 900,
        "auto_prompt_max_silence_ratio": 0.38,
        "auto_prompt_max_nonsilent_chunks": 7,
        "auto_prompt_min_dbfs": -38,
        "auto_prompt_target_dbfs": -20,
        "auto_prompt_peak_dbfs": -3,
        "emo_mode": 0,
        "emo_weight": 0.65,
        "use_random": False,
        "max_text_tokens_per_segment": 120,
        "do_sample": True,
        "top_p": 0.8,
        "top_k": 30,
        "temperature": 0.8,
        "length_penalty": 0.0,
        "num_beams": 3,
        "repetition_penalty": 10.0,
        "max_mel_tokens": 1815,
        "timeout_sec": 300,
    },
    "sf_fish_tts": {
        "api_key": "",
        "voice": "anna",
        "custom_name": "",
        "voice_id": "",
        "mode": "preset",
    },
    "openai_tts": {
        "api_key": "",
        "voice": "alloy",
    },
    "azure_tts": {
        "api_key": "",
        "voice": "zh-CN-YunfengNeural",
    },
    "fish_tts": {
        "api_key": "",
        "character": "AD\u5b66\u59d0",
        "character_id_dict": {
            "AD\u5b66\u59d0": "7f92f8afb8ec43bf81429cc1c9199cb1",
            "\u4e01\u771f": "54a5170264694bfc8e9ad98df7bd89c3",
        },
    },
    "sf_cosyvoice2": {
        "api_key": "",
    },
    "edge_tts": {
        "voice": "zh-CN-XiaoxiaoNeural",
    },
    "gpt_sovits": {
        "character": "",
        "refer_mode": 3,
    },
    "f5tts": {
        "302_api": "",
    },
    "custom_tts": {
        "mode": "python_callable",
        "python_callable": "",
        "command": [],
        "placeholder_audio": "",
    },
    "dub_audio": {
        "bitrate": "192k",
        "sample_rate": 24000,
        "publish_lead_in_ms": 300,
        "publish_line_gap_ms": 180,
        "publish_row_gap_ms": 260,
        "publish_source_gap_scale": 0.45,
        "publish_min_source_gap_sec": 0.12,
        "publish_max_source_gap_sec": 6.0,
        "publish_preserve_short_source_windows": False,
        "publish_tail_pad_ms": 500,
        "publish_global_audio_speed": True,
        "publish_target_video_speed_min": 0.88,
        "publish_max_audio_speed": 1.22,
        "publish_short_video_speed_max": 1.05,
        "publish_short_video_speed_hard_max": 1.08,
        "video_retime": True,
        "video_retime_fps_mode": "cfr",
        "video_speed_warn_min": 0.75,
        "video_speed_warn_max": 1.35,
        "background_ducking": True,
        "background_bed_mode": "separated",
        "background_duck_volume": 0.35,
        "background_duck_high_coverage_threshold": 0.85,
        "background_duck_high_coverage_volume": 0.35,
        "background_duck_padding_ms": 120,
        "background_duck_merge_gap_ms": 700,
        "background_duck_transition_ms": 600,
        "background_duck_filter": True,
        "background_duck_lowpass_hz": 4200,
        "source_bed_duck_volume": 0.12,
        "source_bed_lowpass_hz": 3600,
        "final_loudnorm": True,
        "final_loudnorm_i": -16,
        "final_loudnorm_tp": -1.5,
        "final_loudnorm_lra": 4.5,
        "final_smooth": False,
        "final_smooth_preset": "broadcast",
        "final_smooth_threshold_db": -30.0,
        "final_smooth_ratio": 4.0,
        "final_smooth_attack_ms": 6.0,
        "final_smooth_release_ms": 550.0,
        "final_smooth_makeup_db": 5.5,
        "final_audio_sample_rate": 48000,
        "final_audio_channels": 2,
        "tts_segment_fade_in_ms": 5,
        "tts_segment_fade_out_ms": 220,
        "tts_segment_tail_pad_ms": 220,
        "tts_segment_tail_cleanup": True,
        "tts_segment_tail_cleanup_ms": 420,
        "tts_segment_tail_cleanup_lowpass_hz": 3600,
    },
    "model_dir": "./_model_cache",
    "allowed_video_formats": ["mp4", "mov", "avi", "mkv", "flv", "wmv", "webm"],
    "allowed_audio_formats": ["wav", "mp3", "flac", "m4a"],
    "spacy_model_map": {
        "en": "en_core_web_md",
        "ru": "ru_core_news_md",
        "fr": "fr_core_news_md",
        "ja": "ja_core_news_md",
        "es": "es_core_news_md",
        "de": "de_core_news_md",
        "it": "it_core_news_md",
        "zh": "zh_core_web_md",
    },
    "language_split_with_space": ["en", "es", "fr", "de", "it", "ru"],
    "language_split_without_space": ["zh", "ja"],
    "media": {
        "ffmpeg_path": "ffmpeg",
        "ffprobe_path": "ffprobe",
        "ffmpeg_gpu": False,
    },
    "render": {
        "render_audio": True,
        "render_video": True,
        "burn_subtitles": False,
    },
}
