from __future__ import annotations


LANGUAGE_OPTIONS = {
    "中文": "zh-CN",
    "English": "en",
}


TEXT = {
    "zh-CN": {
        "app_subtitle": "面向发布的中文视频译配工作台",
        "hero_publish": "发布优先",
        "hero_cover": "封面候选",
        "batch_ready": "批量就绪",
        "batch_video_title": "批量视频 {n}",
        "cover": "封面",
        "cover_caption": "从源视频采样生成候选封面",
        "cover_title": "封面标题",
        "cover_subtitle": "副标题",
        "cover_accent": "角标",
        "cover_title_placeholder": "输入醒目的封面标题",
        "cover_subtitle_placeholder": "可选补充说明",
        "cover_accent_placeholder": "可选，如 Eistara",
        "generate_covers": "生成封面候选",
        "cover_source_missing": "请先下载或上传源视频。",
        "cover_ready": "封面候选已生成",
        "cover_contact_sheet": "采样预览",
        "cover_candidates": "候选封面",
        "cover_template": "封面模板",
        "cover_template_cinema": "电影标题",
        "cover_template_news": "资讯横条",
        "cover_template_clean": "干净大字",
        "cover_download": "下载封面",
        "cover_failed": "封面生成失败",
        "single_video": "单视频",
        "batch": "批量任务",
        "history": "历史",
        "history_caption": "批量完成或单视频手动归档后的任务会保存在这里。",
        "history_job": "历史任务",
        "history_outputs": "历史交付物",
        "no_history_jobs": "暂无历史任务",
        "location": "位置",
        "choose_delivery_mode": "选择交付模式",
        "delivery_mode_caption": "先决定这次任务面向阅读字幕，还是面向中文口播成片。",
        "mode_strategy_notice": "字幕模式面向阅读交付，优先控制分行、字数和阅读速度；配音模式面向中文口播成片，优先保证翻译自然、适合 TTS 和混音。两种模式的翻译策略不同，字幕优先模式产生的字幕不可以用来生成配音。",
        "subtitle_mode_kicker": "Reading delivery",
        "subtitle_mode_title": "生成字幕",
        "subtitle_mode_body": "生成网飞级别字幕，优先处理断句、分行、字数和阅读速度，适合直接交付字幕文件。",
        "dubbing_mode_kicker": "Spoken dubbing",
        "dubbing_mode_title": "生成配音",
        "dubbing_mode_body": "生成中文口播成片，翻译优先自然、顺口，后续会进入 TTS、混音和合成。",
        "enter_subtitle_mode": "进入字幕模式",
        "enter_dubbing_mode": "进入配音模式",
        "current_delivery_mode": "当前模式",
        "switch_delivery_mode": "切换模式",
        "subtitle_workspace": "字幕工作台",
        "subtitle_workspace_caption": "字幕优先模式的页面框架已就位，后续接入独立字幕流水线。",
        "subtitle_mode_notice": "此模式只生成阅读交付字幕，不会进入配音、TTS 或混音流程。",
        "subtitle_delivery_focus": "字幕交付重点",
        "subtitle_focus_line_breaks": "控制分行",
        "subtitle_focus_char_limits": "控制字数",
        "subtitle_focus_reading_speed": "控制阅读速度",
        "subtitle_mode_boundary": "模式边界",
        "subtitle_no_dubbing_warning": "字幕优先模式产生的字幕不可以用来生成配音。需要配音时，请从配音模式重新创建任务。",
        "language": "界面语言",
        "source": "素材",
        "translate": "字幕与翻译",
        "dub": "配音与成片",
        "source_ready": "素材已就绪",
        "source_task_ready": "素材任务已创建",
        "source_empty": "等待选择素材",
        "preview_source_video": "预览源视频",
        "preview_final_video": "预览配音成片",
        "download_url": "视频链接",
        "download_or_upload": "下载或上传",
        "download_video": "下载视频",
        "upload_video": "上传本地视频",
        "use_uploaded_file": "使用上传文件",
        "delete_source": "删除并重选",
        "resolution": "分辨率",
        "start_subtitles": "开始字幕翻译",
        "subtitles_done": "字幕已生成",
        "start_dubbing": "开始配音合成",
        "dubbing_done": "配音成片已生成",
        "subtitle_outputs": "字幕交付物",
        "final_outputs": "最终交付物",
        "download_subtitles": "下载字幕包",
        "rebuild_mix": "重建混音成片",
        "regenerate_tts": "重生成配音成片",
        "archive_to_history": "归档到历史",
        "archived_to_history": "已归档到历史",
        "running": "运行中",
        "paused": "已暂停",
        "resume": "继续",
        "pause": "暂停",
        "stop": "停止",
        "task_done": "任务完成",
        "task_stopped": "任务已停止",
        "task_error": "任务出错",
        "ok": "确认",
        "create_source_first": "请先下载或上传素材。",
        "finish_subtitles_first": "请先完成字幕翻译。",
        "add_video_first": "请先添加至少一个视频链接或本地路径。",
        "create_jobs_first": "请先创建任务。",
        "jobs_ready": "任务已创建",
        "batch_jobs_dir": "当前任务目录",
        "batch_concurrency_hint": "批量流水线使用配置中的并发参数；翻译和 TTS 默认单路运行。",
        "batch_sources": "视频列表",
        "batch_sources_placeholder": "每行一个视频链接或本地视频路径",
        "source_language": "源语言",
        "target_language": "目标语言",
        "source_language_english": "英语",
        "source_language_auto": "自动检测",
        "source_language_chinese": "简体中文",
        "target_simplified_chinese": "简体中文",
        "create_jobs": "创建任务",
        "start_batch": "启动批量",
        "stop_batch": "停止批量",
        "reset_failed": "重置失败",
        "recover_interrupted": "恢复中断任务",
        "no_batch_jobs": "暂无批量任务",
        "scheduler_running": "调度器运行中",
        "scheduler_started": "调度器已启动",
        "scheduler_stopped": "调度器已停止，运行中的任务已回到待处理状态。",
        "scheduler_lock_stale": "检测到残留锁，但没有运行中的调度器。",
        "scheduler_recovery_needed": "检测到调度器残留状态，需要恢复。",
        "failed_reset_done": "已重置失败任务",
        "recovered_jobs": "已恢复任务",
        "finished_outputs": "完成输出",
        "job_messages": "任务消息",
        "diagnostics": "诊断",
        "diagnostic_hint": "复制摘要或生成诊断包发给维护者。诊断包只包含脱敏配置、状态文件和裁剪后的日志尾部。",
        "diagnostic_copy": "诊断摘要",
        "diagnostic_build_package": "生成诊断包",
        "diagnostic_download_package": "下载诊断包",
        "diagnostic_package_ready": "诊断包已生成",
        "diagnostic_missing_artifacts": "缺失文件",
        "diagnostic_recent_events": "最近事件",
        "diagnostic_outputs": "已发现交付物",
        "diagnostic_internal_artifacts": "内部诊断文件",
        "recovery_actions": "恢复操作",
        "retry_job": "重试任务",
        "retry_job_done": "任务已回到待处理状态",
        "reset_from_stage": "从阶段重置",
        "reset_job_from_stage": "重置并重跑",
        "reset_job_done": "任务已从所选阶段重置",
        "job": "任务",
        "status": "状态",
        "stage": "阶段",
        "progress": "进度",
        "updated": "更新时间",
        "title_or_source": "标题/来源",
        "done": "完成",
        "failed": "失败",
        "active": "运行",
        "pipeline_lanes": "流水线资源槽",
        "stage_matrix": "阶段矩阵",
        "caption_source": "字幕来源",
        "error_summary": "错误摘要",
        "artifact_role": "用途",
        "artifact_file": "文件",
        "artifact_kind": "类型",
        "artifact_size": "大小",
        "artifact_path": "路径",
        "llm_configuration": "LLM 配置",
        "api_key": "API_KEY",
        "base_url": "BASE_URL",
        "model": "MODEL",
        "fetch_model_list": "拉取模型列表",
        "fetching_models": "正在拉取模型列表...",
        "fetched_models": "已拉取 {n} 个模型",
        "fetch_models_failed": "模型列表拉取失败，请检查 API Key 和 Base URL。",
        "search_or_enter_model": "搜索或输入模型名",
        "check_api": "检查 API",
        "checking_api": "正在检查 API...",
        "api_key_valid": "API Key 有效",
        "api_key_invalid": "API Key 无效",
        "llm_json_support": "LLM JSON Format Support",
        "advanced_runtime": "高级运行参数",
        "advanced_runtime_hint": "迁移和调试用；普通使用一般不需要修改。",
        "config_restart_hint": "重启 launch.py 后该 config path 才会成为进程默认值。",
        "subtitles_settings": "字幕设置",
        "recognition_language": "识别语言",
        "whisper_runtime": "语音识别运行方式",
        "whisper_model": "本地 WhisperX 模型",
        "whisper_302_key": "302 WhisperX API Key",
        "elevenlabs_asr_key": "ElevenLabs ASR API Key",
        "asr_status": "ASR 状态",
        "asr_status_ready": "可用",
        "asr_status_missing": "缺少必要依赖或配置",
        "asr_status_unknown": "未检测",
        "asr_dependency_check": "ASR 能力检查",
        "vocal_separation": "人声分离增强",
        "vocal_provider": "分离后端",
        "vocal_provider_demucs": "Demucs（默认）",
        "vocal_provider_audio_separator": "Audio Separator / UVR-MDX",
        "vocal_model": "分离模型",
        "vocal_model_dir": "模型目录",
        "vocal_model_status": "分离模型状态",
        "vocal_model_ready": "模型已就绪",
        "vocal_model_missing": "模型缺失",
        "vocal_model_invalid": "模型校验失败",
        "vocal_model_unknown": "模型未校验",
        "dubbing_settings": "配音设置",
        "tts_source": "TTS来源",
        "tts_source_local": "本地TTS",
        "tts_source_remote": "网络TTS",
        "tts_method": "TTS方法",
        "tts_audio_rules": "通用TTS音频规则",
        "tts_audio_postprocess": "启用通用后处理",
        "tts_audio_trim_silence": "裁剪首尾静音",
        "tts_audio_lowpass": "片段低通",
        "tts_audio_peak": "峰值上限 dBFS",
        "tts_micro_merge": "合并过短台词",
        "tts_micro_chars": "过短台词字数阈值",
        "dubbing_timeline": "配音时间线",
        "timeline_publish": "发布优先自然配音",
        "publish_mix": "发布混音",
        "minimum_video_speed": "最低视频速度",
        "max_global_dub_speed": "整体配音最大加速",
        "background_bed": "背景音来源",
        "background_separated": "分离背景音（推荐）",
        "background_source_ducked": "原视频压低作背景（可能残留英文）",
        "source_bed_warning": "原视频背景会保留原声轨，只建议诊断或特殊情况使用；发布默认推荐分离背景音。",
        "source_duck_volume": "原视频背景音量",
        "source_duck_lowpass": "原视频背景低通",
        "high_coverage_background": "高覆盖配音背景音量",
        "final_loudness_normalize": "最终响度标准化",
        "target_lufs": "目标 LUFS",
        "whisper_runtime_local": "本地",
        "whisper_runtime_cloud": "云端",
        "whisper_runtime_elevenlabs": "ElevenLabs",
        "youtube_cookies": "YouTube Cookies",
        "cookie_source": "Browser cookie source",
        "browser_profile": "Browser profile",
        "apply_cookie_source": "Apply YouTube Cookie Source",
        "current_cookie_source": "Current source",
        "not_configured": "not configured",
        "indextts_status": "IndexTTS",
    },
    "en": {
        "app_subtitle": "Publish-first Chinese video dubbing workspace",
        "hero_publish": "Publish first",
        "hero_cover": "Cover candidates",
        "batch_ready": "Batch ready",
        "batch_video_title": "Batch Video {n}",
        "cover": "Cover",
        "cover_caption": "Sample the source video and generate cover candidates",
        "cover_title": "Cover title",
        "cover_subtitle": "Subtitle",
        "cover_accent": "Accent",
        "cover_title_placeholder": "Enter a strong cover title",
        "cover_subtitle_placeholder": "Optional supporting line",
        "cover_accent_placeholder": "Optional, e.g. Eistara",
        "generate_covers": "Generate cover candidates",
        "cover_source_missing": "Download or upload a source video first.",
        "cover_ready": "Cover candidates generated",
        "cover_contact_sheet": "Contact sheet",
        "cover_candidates": "Cover candidates",
        "cover_template": "Cover template",
        "cover_template_cinema": "Cinematic title",
        "cover_template_news": "News banner",
        "cover_template_clean": "Clean headline",
        "cover_download": "Download cover",
        "cover_failed": "Cover generation failed",
        "single_video": "Single Video",
        "batch": "Batch",
        "history": "History",
        "history_caption": "Completed jobs are archived here after batch completion or manual single-video archive.",
        "history_job": "History job",
        "history_outputs": "Archived deliverables",
        "no_history_jobs": "No archived jobs yet",
        "location": "Location",
        "choose_delivery_mode": "Choose delivery mode",
        "delivery_mode_caption": "Start by choosing whether this task is for readable subtitles or a Chinese dubbed video.",
        "mode_strategy_notice": "Subtitle mode is for reading delivery and prioritizes line breaks, character limits, and reading speed. Dubbing mode is for Chinese spoken video and prioritizes natural translation for TTS and mixing. The translation strategies are different, and subtitle-priority output cannot be used to generate dubbing.",
        "subtitle_mode_kicker": "Reading delivery",
        "subtitle_mode_title": "Generate Subtitles",
        "subtitle_mode_body": "Generate high-quality subtitles with priority on segmentation, line breaks, character limits, and reading speed.",
        "dubbing_mode_kicker": "Spoken dubbing",
        "dubbing_mode_title": "Generate Dubbing",
        "dubbing_mode_body": "Generate a Chinese dubbed video with natural spoken translation, TTS, mixing, and final composition.",
        "enter_subtitle_mode": "Enter subtitle mode",
        "enter_dubbing_mode": "Enter dubbing mode",
        "current_delivery_mode": "Current mode",
        "switch_delivery_mode": "Switch mode",
        "subtitle_workspace": "Subtitle Workspace",
        "subtitle_workspace_caption": "The subtitle-first UI framework is ready; the independent subtitle pipeline can be connected next.",
        "subtitle_mode_notice": "This mode only generates reading-delivery subtitles. It does not enter dubbing, TTS, or mixing.",
        "subtitle_delivery_focus": "Subtitle delivery focus",
        "subtitle_focus_line_breaks": "Control line breaks",
        "subtitle_focus_char_limits": "Control character limits",
        "subtitle_focus_reading_speed": "Control reading speed",
        "subtitle_mode_boundary": "Mode boundary",
        "subtitle_no_dubbing_warning": "Subtitle-priority output cannot be used to generate dubbing. Create a new task in dubbing mode when dubbing is needed.",
        "language": "Language",
        "source": "Source",
        "translate": "Subtitles & Translation",
        "dub": "Dubbing & Export",
        "source_ready": "Source ready",
        "source_task_ready": "Source job ready",
        "source_empty": "Select a source",
        "preview_source_video": "Preview source video",
        "preview_final_video": "Preview dubbed video",
        "download_url": "Video URL",
        "download_or_upload": "Download or upload",
        "download_video": "Download Video",
        "upload_video": "Upload local video",
        "use_uploaded_file": "Use uploaded file",
        "delete_source": "Delete and reselect",
        "resolution": "Resolution",
        "start_subtitles": "Start subtitle translation",
        "subtitles_done": "Subtitles generated",
        "start_dubbing": "Start dubbing export",
        "dubbing_done": "Dubbed video generated",
        "subtitle_outputs": "Subtitle deliverables",
        "final_outputs": "Final deliverables",
        "download_subtitles": "Download subtitles",
        "rebuild_mix": "Rebuild mix + video",
        "regenerate_tts": "Regenerate TTS + video",
        "archive_to_history": "Archive to history",
        "archived_to_history": "Archived to history",
        "running": "Running",
        "paused": "Paused",
        "resume": "Resume",
        "pause": "Pause",
        "stop": "Stop",
        "task_done": "Task completed",
        "task_stopped": "Task stopped",
        "task_error": "Task error",
        "ok": "OK",
        "create_source_first": "Download or upload a source first.",
        "finish_subtitles_first": "Finish subtitles before dubbing.",
        "add_video_first": "Add at least one video URL or local path.",
        "create_jobs_first": "Create jobs first.",
        "jobs_ready": "Jobs ready",
        "batch_jobs_dir": "Active jobs directory",
        "batch_concurrency_hint": "Batch uses configured concurrency values. Translation and TTS run as single bottleneck lanes by default.",
        "batch_sources": "Videos",
        "batch_sources_placeholder": "One YouTube URL or local video path per line",
        "source_language": "Source language",
        "target_language": "Target language",
        "source_language_english": "English",
        "source_language_auto": "Auto detect",
        "source_language_chinese": "Simplified Chinese",
        "target_simplified_chinese": "Simplified Chinese",
        "create_jobs": "Create jobs",
        "start_batch": "Start batch",
        "stop_batch": "Stop batch",
        "reset_failed": "Reset failed",
        "recover_interrupted": "Recover interrupted jobs",
        "no_batch_jobs": "No batch jobs yet",
        "scheduler_running": "Scheduler running",
        "scheduler_started": "Scheduler started",
        "scheduler_stopped": "Scheduler stopped. Running jobs were returned to pending.",
        "scheduler_lock_stale": "Scheduler lock exists, but no running scheduler process was detected.",
        "scheduler_recovery_needed": "Scheduler recovery is needed.",
        "failed_reset_done": "Reset failed jobs",
        "recovered_jobs": "Recovered jobs",
        "finished_outputs": "Finished outputs",
        "job_messages": "Job messages",
        "diagnostics": "Diagnostics",
        "diagnostic_hint": "Copy the summary or generate a diagnostic package for maintainers. The package contains redacted config, state files, and truncated log tails only.",
        "diagnostic_copy": "Diagnostic summary",
        "diagnostic_build_package": "Build diagnostic package",
        "diagnostic_download_package": "Download diagnostic package",
        "diagnostic_package_ready": "Diagnostic package is ready",
        "diagnostic_missing_artifacts": "Missing files",
        "diagnostic_recent_events": "Recent events",
        "diagnostic_outputs": "Detected deliverables",
        "diagnostic_internal_artifacts": "Internal diagnostic files",
        "recovery_actions": "Recovery actions",
        "retry_job": "Retry job",
        "retry_job_done": "Job returned to pending",
        "reset_from_stage": "Reset from stage",
        "reset_job_from_stage": "Reset and rerun",
        "reset_job_done": "Job was reset from the selected stage",
        "job": "Job",
        "status": "Status",
        "stage": "Stage",
        "progress": "Progress",
        "updated": "Updated",
        "title_or_source": "Title/source",
        "done": "Done",
        "failed": "Failed",
        "active": "Running",
        "pipeline_lanes": "Pipeline lanes",
        "stage_matrix": "Stage matrix",
        "caption_source": "Caption source",
        "error_summary": "Error summary",
        "artifact_role": "Role",
        "artifact_file": "File",
        "artifact_kind": "Kind",
        "artifact_size": "Size",
        "artifact_path": "Path",
        "llm_configuration": "LLM Configuration",
        "api_key": "API_KEY",
        "base_url": "BASE_URL",
        "model": "MODEL",
        "fetch_model_list": "Fetch Model List",
        "fetching_models": "Fetching models...",
        "fetched_models": "Fetched {n} models",
        "fetch_models_failed": "Failed to fetch models. Check API Key and Base URL.",
        "search_or_enter_model": "Search or enter model name",
        "check_api": "Check API",
        "checking_api": "Checking API...",
        "api_key_valid": "API Key is valid",
        "api_key_invalid": "API Key is invalid",
        "llm_json_support": "LLM JSON Format Support",
        "advanced_runtime": "Advanced runtime",
        "advanced_runtime_hint": "For debugging. Normal use usually does not need this.",
        "config_restart_hint": "Restart launch.py for this config path to become the process default.",
        "subtitles_settings": "Subtitles Settings",
        "recognition_language": "Recognition language",
        "whisper_runtime": "ASR Runtime",
        "whisper_model": "Local WhisperX model",
        "whisper_302_key": "302 WhisperX API Key",
        "elevenlabs_asr_key": "ElevenLabs ASR API Key",
        "asr_status": "ASR status",
        "asr_status_ready": "ready",
        "asr_status_missing": "missing required dependency or config",
        "asr_status_unknown": "not checked",
        "asr_dependency_check": "ASR capability check",
        "vocal_separation": "Vocal separation enhance",
        "vocal_provider": "Separation backend",
        "vocal_provider_demucs": "Demucs (default)",
        "vocal_provider_audio_separator": "Audio Separator / UVR-MDX",
        "vocal_model": "Separation model",
        "vocal_model_dir": "Model directory",
        "vocal_model_status": "Separation model status",
        "vocal_model_ready": "model ready",
        "vocal_model_missing": "model missing",
        "vocal_model_invalid": "model failed validation",
        "vocal_model_unknown": "model not validated",
        "dubbing_settings": "Dubbing Settings",
        "tts_source": "TTS source",
        "tts_source_local": "Local TTS",
        "tts_source_remote": "Network TTS",
        "tts_method": "TTS method",
        "tts_audio_rules": "Shared TTS audio rules",
        "tts_audio_postprocess": "Enable shared postprocess",
        "tts_audio_trim_silence": "Trim leading/trailing silence",
        "tts_audio_lowpass": "Segment low-pass",
        "tts_audio_peak": "Peak ceiling dBFS",
        "tts_micro_merge": "Merge very short lines",
        "tts_micro_chars": "Short-line character threshold",
        "dubbing_timeline": "Dubbing timeline",
        "timeline_publish": "Publish-first natural dubbing",
        "publish_mix": "Publish mix",
        "minimum_video_speed": "Minimum video speed",
        "max_global_dub_speed": "Max global dub speed",
        "background_bed": "Background bed",
        "background_separated": "Separated background (recommended)",
        "background_source_ducked": "Original source bed (may leak speech)",
        "source_bed_warning": "Original source bed keeps the source vocal track. Use it only for diagnostics or special cases; separated background is recommended for publishing.",
        "source_duck_volume": "Source duck volume",
        "source_duck_lowpass": "Source duck lowpass",
        "high_coverage_background": "High-coverage background",
        "final_loudness_normalize": "Final loudness normalize",
        "target_lufs": "Target LUFS",
        "whisper_runtime_local": "Local",
        "whisper_runtime_cloud": "Cloud",
        "whisper_runtime_elevenlabs": "ElevenLabs",
        "youtube_cookies": "YouTube Cookies",
        "cookie_source": "Browser cookie source",
        "browser_profile": "Browser profile",
        "apply_cookie_source": "Apply YouTube Cookie Source",
        "current_cookie_source": "Current source",
        "not_configured": "not configured",
        "indextts_status": "IndexTTS",
    },
}


def normalize_language(value: str | None) -> str:
    return "zh-CN" if str(value or "").startswith("zh") else "en"


def ui_t(language: str, key: str) -> str:
    normalized = normalize_language(language)
    return TEXT.get(normalized, TEXT["zh-CN"]).get(key, TEXT["en"].get(key, key))
